### ISSUE TITLE
Automatically add 'nofollow' to all links

### ISSUE THREAD

**Issue by fisharebest** [IET-OU/cloudengine#339] opened 2014-06-05 11:40 UTC
Due to occasional spam, add nofollow to all links on the sites, in particular those on prfiles. 

---
- Bitbucket: https://bitbucket.org/cloudengine/cloudengine/issue/339
- Originally Reported By: [Juliette Culver](http://bitbucket.org/julietteculver)
- Originally Created At: 2013-03-08T14:59:48.123

**Comment by nfreear** [comment] 2017-11-24 17:36
* Duplicate of: #364.

Closing,

N.

**Closed by nfreear** 2017-11-24 17:36 UTC
